version: '3'
services:
  app.develop:
    container_name: app.develop
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.1/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-8000}:8000'
    env_file:
      - .env
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/app/vendor'
      - '.:/var/www/html/app'
    networks:
      - app-net
    depends_on:
      - mysql
  mysql:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-app_db}"
      MYSQL_PORT: "${DB_PORT:-3306}"
      MYSQL_USERNAME: "${DB_USERNAME:-admin}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
    networks:
      - app-net
    volumes:
      - app_db:/var/lib/mysql/

networks:
  app-net:
    driver: bridge
volumes:
  app_db:
    driver: local
