<link href="assets/plugins/custom/fullcalendar/fullcalendar.bundle.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/plugins/global/plugins.bundle.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/plugins/custom/prismjs/prismjs.bundle.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/css/style.bundle.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/css/themes/layout/header/base/light.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/css/themes/layout/header/menu/light.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/css/themes/layout/brand/dark.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/css/themes/layout/aside/dark.rtl.css" rel="stylesheet" type="text/css" />
<link href="assets/css/style.css" rel="stylesheet" type="text/css" />
